<a href="https://colab.research.google.com/github/rajasreekalli/datascience-dojo/blob/main/Intro_to_Numpy_and_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
quantity_sold = [17, 40, 1]
quantity_sold = np.append(quantity_sold, [2, 3, 16, 5])
print(quantity_sold)

[17 40  1  2  3 16  5]


In [ ]:
quantity_sold[1] = 39
print(quantity_sold)

[17 39  1  2  3 16  5]


In [ ]:
price = [2, 1, 10, 7, 4.50, 3, 4]#brownie, cookie, cake, pie, fudge, cup cakes, bannana bread
type(price)

list

In [ ]:
quantity_sold = [17, 39, 1, 2, 3, 16, 5]#brownie, cookie, cake, pie, fudge, cup cakes, bannana bread
type(quantity_sold)

list

In [ ]:
import numpy as np
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)#brownie, cookie, cake, pie, fudge, cup cakes, bannana bread
type(price_array)

numpy.ndarray

In [ ]:
price_array * quantity_sold_array

array([34. , 39. , 10. , 14. , 13.5, 48. , 20. ])

In [ ]:
quantity_leftover = [0,0,2,1,6,0,2]#brownie, cookie, cake, pie, fudge, cup cakes, bannana bread
print (quantity_leftover) #since it's a list and it's has built-in index which cannot be modified.

[0, 0, 2, 1, 6, 0, 2]


In [ ]:
half_price = price_array / 2
clearence_sale = half_price * quantity_leftover
print(clearence_sale)

[ 0.   0.  10.   3.5 13.5  0.   4. ]


In [45]:
full_price = price_array * quantity_sold_array
total_price = full_price + clearence_sale
print(sum(total_price))

209.5
