<a href="https://colab.research.google.com/github/rajasreekalli/datascience-dojo/blob/main/Intro_to_Numpy_and_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [171]:
import numpy as np

In [214]:
quantity_sold = [17, 40, 1]# brownie, cookies, cake
quantity_sold = np.append(quantity_sold, [2, 3, 16, 5]) #Pie, fudge, cupcakes, bannana_bread
print(quantity_sold)

[17 40  1  2  3 16  5]


In [223]:
quantity_sold[1] = 39
print(quantity_sold)

[17 39  1  2  3 16  5]


In [239]:
price = [2, 1, 12, 7, 4.50, 3, 4]#brownie, cookies, cake, pie, fudge, cup cakes, bannana_bread
print(price)

[2, 1, 12, 7, 4.5, 3, 4]


In [253]:
quantity_sold = [17, 39, 1, 2, 3, 16, 5]#brownie, cookie, cake, pie, fudge, cup cakes, bannana_bread
type(quantity_sold)

list

In [254]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)#brownie, cookie, cake, pie, fudge, cup cakes, bannana_bread
price_array

array([ 2. ,  1. , 12. ,  7. ,  4.5,  3. ,  4. ])

In [255]:
price_array * quantity_sold_array

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

In [256]:
quantity_leftover = [0,0,2,1,6,0,2]#brownie, cookie, cake, pie, fudge, cup cakes, bannana bread
print (quantity_leftover) #since it's a list and it's has built-in index which cannot be modified.

[0, 0, 2, 1, 6, 0, 2]


In [257]:
half_price = price_array / 2
clearence_sale = half_price * quantity_leftover
print(clearence_sale)

[ 0.   0.  12.   3.5 13.5  0.   4. ]


In [258]:
full_price = price_array * quantity_sold_array
total_price = full_price + clearence_sale
print(sum(total_price))

213.5
